// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YCR.Infrastructure.Persistence;

#nullable disable

namespace YCR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YcrDbContext))]
    [Migration("20260927072142_Security_TimetableScheduleGrants")]
    partial class Security_TimetableScheduleGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuthSessions_UserId");

                    b.ToTable("AuthSessions", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_AuthSessions_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AuthSessions_ExpiresAtUtc_Utc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AuthSessions_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AuthSessions_RevocationReason", "[RevocationReason] IN (N'Logout', N'PasswordChanged', N'AdministratorPasswordReset', N'UserDisabled', N'AdministratorRevoked', N'FamilyReuse')");

                            t.HasCheckConstraint("CK_AuthSessions_Revocation_Consistent", "([RevokedAtUtc] IS NULL AND [RevocationReason] IS NULL) OR ([RevokedAtUtc] IS NOT NULL AND [RevocationReason] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AuthSessions_RevokedAtUtc_Utc", "DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_ReplacedByTokenId")
                        .HasFilter("[ReplacedByTokenId] IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_RefreshTokens_SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.ToTable("RefreshTokens", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_IssuedAtUtc_Utc", "DATEPART(TZOFFSET, [IssuedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_NotSelf", "[ReplacedByTokenId] <> [Id]");

                            t.HasCheckConstraint("CK_RefreshTokens_RotatedAtUtc_Utc", "DATEPART(TZOFFSET, [RotatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_Rotation_Consistent", "([RotatedAtUtc] IS NULL AND [ReplacedByTokenId] IS NULL) OR ([RotatedAtUtc] IS NOT NULL AND [ReplacedByTokenId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("YCR.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_RolePermissions_Permission_Format", "[Permission] COLLATE Latin1_General_100_BIN2 NOT LIKE N'%[^-a-z.]%'");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUserName");

                    b.ToTable("Users", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Users_AccessFailedCount", "[AccessFailedCount] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_Users_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_DisabledAtUtc_Utc", "DATEPART(TZOFFSET, [DisabledAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_Disabled_Consistent", "([IsDisabled] = 1 AND [DisabledAtUtc] IS NOT NULL) OR ([IsDisabled] = 0 AND [DisabledAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_Users_LockoutEndUtc_Utc", "DATEPART(TZOFFSET, [LockoutEndUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_PasswordChangedAtUtc_Utc", "DATEPART(TZOFFSET, [PasswordChangedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_UserName_Format", "LEN([UserName]) BETWEEN 3 AND 50 AND [UserName] COLLATE Latin1_General_100_BIN2 NOT LIKE N'%[^a-z0-9.]%'");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("YCR.Domain.Network.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_Routes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Routes_Code");

                    b.ToTable("Routes", "network", t =>
                        {
                            t.HasCheckConstraint("CK_Routes_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Routes_DeactivatedAtUtc_Utc", "[DeactivatedAtUtc] IS NULL OR DATEPART(TZOFFSET, [DeactivatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Network.RouteStation", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RouteId", "Position")
                        .HasName("PK_RouteStations");

                    b.HasIndex("StationId", "RouteId")
                        .IsUnique()
                        .HasDatabaseName("UX_RouteStations_StationId_RouteId");

                    b.ToTable("RouteStations", "network", t =>
                        {
                            t.HasCheckConstraint("CK_RouteStations_Position", "[Position] >= 1");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Stations_Code");

                    b.ToTable("Stations", "network", t =>
                        {
                            t.HasCheckConstraint("CK_Stations_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleStopTime", b =>
                {
                    b.Property<Guid>("ScheduleVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<short?>("Arrival")
                        .HasColumnType("smallint")
                        .HasColumnName("ArrivalMinute");

                    b.Property<short?>("Departure")
                        .HasColumnType("smallint")
                        .HasColumnName("DepartureMinute");

                    b.HasKey("ScheduleVersionId", "ServiceId", "Position")
                        .HasName("PK_ScheduleStopTimes");

                    b.HasIndex("ServiceId", "Position")
                        .HasDatabaseName("IX_ScheduleStopTimes_ServiceId_Position");

                    b.ToTable("ScheduleStopTimes", "timetable", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduleStopTimes_AnyTime", "[ArrivalMinute] IS NOT NULL OR [DepartureMinute] IS NOT NULL");

                            t.HasCheckConstraint("CK_ScheduleStopTimes_Dwell", "[ArrivalMinute] IS NULL OR [DepartureMinute] IS NULL OR [DepartureMinute] >= [ArrivalMinute]");

                            t.HasCheckConstraint("CK_ScheduleStopTimes_Minutes", "([ArrivalMinute] IS NULL OR [ArrivalMinute] BETWEEN 0 AND 1439) AND ([DepartureMinute] IS NULL OR [DepartureMinute] BETWEEN 0 AND 1439)");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("DiscardedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK_ScheduleVersions");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_ScheduleVersions_EffectiveFrom_Published")
                        .HasFilter("[Status] = N'Published'");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UX_ScheduleVersions_Number");

                    b.ToTable("ScheduleVersions", "timetable", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduleVersions_CancelledAtUtc_Utc", "[CancelledAtUtc] IS NULL OR DATEPART(TZOFFSET, [CancelledAtUtc]) = 0");

                            t.HasCheckConstraint("CK_ScheduleVersions_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_ScheduleVersions_DiscardedAtUtc_Utc", "[DiscardedAtUtc] IS NULL OR DATEPART(TZOFFSET, [DiscardedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_ScheduleVersions_Number", "[Number] >= 1");

                            t.HasCheckConstraint("CK_ScheduleVersions_PublishedAtUtc_Utc", "[PublishedAtUtc] IS NULL OR DATEPART(TZOFFSET, [PublishedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_ScheduleVersions_Status", "[Status] IN (N'Draft', N'Published', N'Discarded', N'Cancelled')");

                            t.HasCheckConstraint("CK_ScheduleVersions_StatusInstants", "([Status] = N'Draft' AND [PublishedAtUtc] IS NULL AND [DiscardedAtUtc] IS NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = N'Published' AND [PublishedAtUtc] IS NOT NULL AND [DiscardedAtUtc] IS NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = N'Discarded' AND [PublishedAtUtc] IS NULL AND [DiscardedAtUtc] IS NOT NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = N'Cancelled' AND [PublishedAtUtc] IS NOT NULL AND [DiscardedAtUtc] IS NULL AND [CancelledAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersionService", b =>
                {
                    b.Property<Guid>("ScheduleVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleVersionId", "ServiceId")
                        .HasName("PK_ScheduleVersionServices");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ScheduleVersionServices_ServiceId");

                    b.ToTable("ScheduleVersionServices", "timetable");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .IsConcurrencyToken()
                        .HasColumnType("date");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.HasKey("Id")
                        .HasName("PK_Services");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("IX_Services_RouteId");

                    b.HasIndex("Code", "EffectiveFrom")
                        .HasDatabaseName("IX_Services_Code_EffectiveFrom");

                    b.ToTable("Services", "timetable", t =>
                        {
                            t.HasCheckConstraint("CK_Services_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Services_Direction", "[Direction] IN (N'Forward', N'Reverse')");

                            t.HasCheckConstraint("CK_Services_EffectivePeriod", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom] OR [WithdrawnAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("CK_Services_OperatingDays", "[RunsOnMonday] = 1 OR [RunsOnTuesday] = 1 OR [RunsOnWednesday] = 1 OR [RunsOnThursday] = 1 OR [RunsOnFriday] = 1 OR [RunsOnSaturday] = 1 OR [RunsOnSunday] = 1");

                            t.HasCheckConstraint("CK_Services_WithdrawnAtUtc_Utc", "[WithdrawnAtUtc] IS NULL OR DATEPART(TZOFFSET, [WithdrawnAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ServiceStop", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceId", "Position")
                        .HasName("PK_ServiceStops");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_ServiceStops_StationId");

                    b.ToTable("ServiceStops", "timetable", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceStops_Position", "[Position] >= 1");
                        });
                });

            modelBuilder.Entity("YCR.Infrastructure.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedByPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", "audit", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("CK_AuditEvents_OccurredAtUtc_Utc", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.HasOne("YCR.Domain.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("YCR.Domain.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("YCR.Domain.Identity.AuthSession", null)
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("YCR.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("YCR.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("YCR.Domain.Identity.StaffUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Network.Route", b =>
                {
                    b.OwnsOne("YCR.Domain.Common.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes", "network");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Network.RouteStation", b =>
                {
                    b.HasOne("YCR.Domain.Network.Route", null)
                        .WithMany("Stations")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RouteStations_Routes_RouteId");

                    b.HasOne("YCR.Domain.Network.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RouteStations_Stations_StationId");
                });

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.OwnsOne("YCR.Domain.Common.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "network");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleStopTime", b =>
                {
                    b.HasOne("YCR.Domain.Timetable.ScheduleVersionService", null)
                        .WithMany("StopTimes")
                        .HasForeignKey("ScheduleVersionId", "ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleStopTimes_ScheduleVersionServices_ScheduleVersionId_ServiceId");

                    b.HasOne("YCR.Domain.Timetable.ServiceStop", null)
                        .WithMany()
                        .HasForeignKey("ServiceId", "Position")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleStopTimes_ServiceStops_ServiceId_Position");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersion", b =>
                {
                    b.OwnsOne("YCR.Domain.Common.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ScheduleVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("ScheduleVersionId");

                            b1.ToTable("ScheduleVersions", "timetable");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleVersionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersionService", b =>
                {
                    b.HasOne("YCR.Domain.Timetable.ScheduleVersion", null)
                        .WithMany("Services")
                        .HasForeignKey("ScheduleVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleVersionServices_ScheduleVersions_ScheduleVersionId");

                    b.HasOne("YCR.Domain.Timetable.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleVersionServices_Services_ServiceId");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.Service", b =>
                {
                    b.HasOne("YCR.Domain.Network.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Services_Routes_RouteId");

                    b.OwnsOne("YCR.Domain.Timetable.OperatingDays", "OperatingDays", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("RunsOnFriday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnFriday");

                            b1.Property<bool>("RunsOnMonday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnMonday");

                            b1.Property<bool>("RunsOnSaturday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnSaturday");

                            b1.Property<bool>("RunsOnSunday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnSunday");

                            b1.Property<bool>("RunsOnThursday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnThursday");

                            b1.Property<bool>("RunsOnTuesday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnTuesday");

                            b1.Property<bool>("RunsOnWednesday")
                                .HasColumnType("bit")
                                .HasColumnName("RunsOnWednesday");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services", "timetable");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("YCR.Domain.Common.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services", "timetable");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OperatingDays")
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ServiceStop", b =>
                {
                    b.HasOne("YCR.Domain.Timetable.Service", null)
                        .WithMany("Stops")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceStops_Services_ServiceId");

                    b.HasOne("YCR.Domain.Network.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceStops_Stations_StationId");
                });

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("YCR.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("YCR.Domain.Identity.StaffUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("YCR.Domain.Network.Route", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersion", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.ScheduleVersionService", b =>
                {
                    b.Navigation("StopTimes");
                });

            modelBuilder.Entity("YCR.Domain.Timetable.Service", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
