// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YCR.Infrastructure.Persistence;

#nullable disable

namespace YCR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YcrDbContext))]
    [Migration("20260923133457_Identity_CreateIdentitySchema")]
    partial class Identity_CreateIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuthSessions_UserId");

                    b.ToTable("AuthSessions", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_AuthSessions_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AuthSessions_ExpiresAtUtc_Utc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_AuthSessions_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AuthSessions_RevocationReason", "[RevocationReason] IN (N'Logout', N'PasswordChanged', N'AdministratorPasswordReset', N'UserDisabled', N'AdministratorRevoked', N'FamilyReuse')");

                            t.HasCheckConstraint("CK_AuthSessions_Revocation_Consistent", "([RevokedAtUtc] IS NULL AND [RevocationReason] IS NULL) OR ([RevokedAtUtc] IS NOT NULL AND [RevocationReason] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AuthSessions_RevokedAtUtc_Utc", "DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_ReplacedByTokenId")
                        .HasFilter("[ReplacedByTokenId] IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_RefreshTokens_SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.ToTable("RefreshTokens", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_IssuedAtUtc_Utc", "DATEPART(TZOFFSET, [IssuedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_NotSelf", "[ReplacedByTokenId] <> [Id]");

                            t.HasCheckConstraint("CK_RefreshTokens_RotatedAtUtc_Utc", "DATEPART(TZOFFSET, [RotatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_RefreshTokens_Rotation_Consistent", "([RotatedAtUtc] IS NULL AND [ReplacedByTokenId] IS NULL) OR ([RotatedAtUtc] IS NOT NULL AND [ReplacedByTokenId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("YCR.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_RolePermissions_Permission_Format", "[Permission] COLLATE Latin1_General_100_BIN2 NOT LIKE N'%[^-a-z.]%'");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUserName");

                    b.ToTable("Users", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Users_AccessFailedCount", "[AccessFailedCount] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_Users_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_DisabledAtUtc_Utc", "DATEPART(TZOFFSET, [DisabledAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_Disabled_Consistent", "([IsDisabled] = 1 AND [DisabledAtUtc] IS NOT NULL) OR ([IsDisabled] = 0 AND [DisabledAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_Users_LockoutEndUtc_Utc", "DATEPART(TZOFFSET, [LockoutEndUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_PasswordChangedAtUtc_Utc", "DATEPART(TZOFFSET, [PasswordChangedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_Users_UserName_Format", "LEN([UserName]) BETWEEN 3 AND 50 AND [UserName] COLLATE Latin1_General_100_BIN2 NOT LIKE N'%[^a-z0-9.]%'");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Stations_Code");

                    b.ToTable("Stations", "network", t =>
                        {
                            t.HasCheckConstraint("CK_Stations_CreatedAtUtc_Utc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Infrastructure.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedByPermission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", "audit", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("CK_AuditEvents_OccurredAtUtc_Utc", "DATEPART(TZOFFSET, [OccurredAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.HasOne("YCR.Domain.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("YCR.Domain.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("YCR.Domain.Identity.AuthSession", null)
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("YCR.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("YCR.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("YCR.Domain.Identity.StaffUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.OwnsOne("YCR.Domain.Network.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "network");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("YCR.Domain.Identity.AuthSession", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("YCR.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("YCR.Domain.Identity.StaffUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
