// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YCR.Infrastructure.Persistence;

#nullable disable

namespace YCR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YcrDbContext))]
    partial class YcrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Stations_Code");

                    b.ToTable("Stations", "network");
                });

            modelBuilder.Entity("YCR.Domain.Network.Station", b =>
                {
                    b.OwnsOne("YCR.Domain.Network.BilingualName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("My")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NameMy");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "network");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
